"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Command;
(function (Command) {
    Command["play"] = "play";
    Command["pause"] = "pause";
    Command["stop"] = "stop";
    Command["nextTrack"] = "nextTrack";
    Command["previousTrack"] = "previousTrack";
    Command["seekForward"] = "seekForward";
    Command["seekBackward"] = "seekBackward";
    Command["seek"] = "seek";
    Command["volume"] = "volume";
    Command["setRating"] = "setRating";
    Command["togglePlayPause"] = "togglePlayPause";
    Command["enableLanguageOption"] = "enableLanguageOption";
    Command["disableLanguageOption"] = "disableLanguageOption";
    Command["skipForward"] = "skipForward";
    Command["skipBackward"] = "skipBackward";
    Command["changePlaybackPosition"] = "changePlaybackPosition";
    Command["closeNotification"] = "closeNotification";
})(Command = exports.Command || (exports.Command = {}));
