require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Uncomment the next line to define a global platform for your project
platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'MusicControl' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
                    
    # to enable hermes or fabric update config file and then install pods
    :hermes_enabled => false,
    :fabric_enabled => false,
                    
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
end

target 'MusicControl-tvOS' do

end
